### ISSUE TITLE
DGAZA(드가자) 팀 쓰기 권한 요청 드립니다.

### ISSUE THREAD

**Issue by coinuniv** [cse-hansung/capstone2021#53]
DGAZA(드가자) 팀 쓰기 권한 요청 드립니다.

**Comment by jyheo** [comment]
본인들이 뭘 하는지 알고 요청한거죠? Pull request 하라고 했는데, issue를 만들었네요? 권한 부여는 했으니 메일 확인하고, 본인들이 뭘 하는지 알면 직접 저장소 수정하면 되고.. 만일 잘 모르는거라면 직접하지 말고 저한테 요청하기 바랍니다.
